# Generated by Django 3.0.8 on 2021-08-07 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(default=None, max_length=40, null=True)),
                ('card_bank', models.CharField(default=None, max_length=40, null=True)),
                ('card_number', models.CharField(default=None, max_length=40, null=True)),
                ('expiry_month', models.CharField(default=None, max_length=40, null=True)),
                ('expiry_year', models.CharField(default=None, max_length=40, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
